from typing import Protocol, runtime_checkable


@runtime_checkable
class Notifier(Protocol):
    """Contract for all notification backends (Discord, Slack, ntfy, Telegram, …)."""

    def notify_recreation_started(self, name: str, image: str) -> None: ...

    def notify_update_success(self, name: str, image: str) -> None: ...

    def notify_dependents_restarted(
        self,
        restarted: list[str],
        failures: list[tuple[str, str]],
    ) -> None: ...

    def notify_failure(self, name: str, reason: str) -> None: ...

    def notify_rollback(self, name: str, success: bool, detail: str = "") -> None: ...

    def notify_summary_report(self, summary: dict) -> None: ...

    def notify_summary(self, title: str, message: str) -> None: ...

    def notify_startup(self, check_interval_seconds: int, hostname: str) -> None: ...

    def notify_shutdown(self, reason: str = "Stopped by user (Ctrl+C).") -> None: ...
